import { normalizeUsername } from "@/lib/username/normalize";

export const RESERVED_USERNAMES = [
  "about",
  "account",
  "account-settings",
  "admin",
  "api",
  "app",
  "auth",
  "billing",
  "blog",
  "careers",
  "complete",
  "conxion",
  "conxionapp",
  "console",
  "connections",
  "control-center",
  "cookie-settings",
  "dashboard",
  "discover",
  "edit",
  "event",
  "events",
  "explore",
  "feed",
  "help",
  "host",
  "hosting",
  "inbox",
  "login",
  "logout",
  "me",
  "member",
  "members",
  "message",
  "messages",
  "network",
  "notifications",
  "official",
  "onboarding",
  "photo-guide",
  "pricing",
  "privacy",
  "profile",
  "profiles",
  "references",
  "requests",
  "root",
  "safety",
  "safety-center",
  "search",
  "settings",
  "shop",
  "signin",
  "signup",
  "subscribe",
  "subscription",
  "subscriptions",
  "support",
  "system",
  "teacher",
  "teachers",
  "team",
  "terms",
  "travel",
  "trips",
  "u",
  "users",
  "verification",
  "verify",
] as const;

const RESERVED_LOOKUP = new Set(RESERVED_USERNAMES.map((value) => normalizeUsername(value)));

export function isReservedUsername(username: string) {
  return RESERVED_LOOKUP.has(normalizeUsername(username));
}
